### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by SpellignErr** [nicoburns/multirun#1]
The readme specifies creating a multirun.toml file. The config.rs specifies multirun.json as the config file. Please change these to match, I would do it but idk which it's supposed to be (brand new to rust here). Also, it might help if you release a default multirun.* file so people have a template to use, even if all of the values are commented out.

**Comment by nicoburns** [comment]
You're absolutely right. I wasn't really expecting anyone outside my company to actually see this repo yet, so I haven't put any effort into making it generally usable. I've changed toml -> json, and added a sample config file to the README.
